(()=>{
'use strict';
const OFFICIAL={
N1:{time:'言語知識（文字・語彙・文法）・讀解 110 分；聽解 55 分',daily:{vocab:14,grammar:12,reading:10,listening:12},mock:{vocab:{kanji:6,context:7,paraphrase:6,usage:6},grammar:{form:10,composition:5,text:5},reading:{short:4,mid:9,long:4,integrated:3,thematic:4,info:2},listening:{task:5,point:6,summary:5,quick:11,integrated:3}}},
N2:{time:'言語知識（文字・語彙・文法）・讀解 105 分；聽解 50 分',daily:{vocab:14,grammar:12,reading:9,listening:12},mock:{vocab:{kanji:5,orthography:5,wordFormation:5,context:7,paraphrase:5,usage:5},grammar:{form:12,composition:5,text:5},reading:{short:5,mid:9,integrated:2,thematic:3,info:2},listening:{task:5,point:6,summary:5,quick:12,integrated:3}}},
N3:{time:'文字・語彙 30 分；文法・讀解 70 分；聽解 40 分',daily:{vocab:14,grammar:10,reading:8,listening:10},mock:{vocab:{kanji:8,orthography:6,context:11,paraphrase:5,usage:5},grammar:{form:13,composition:5,text:5},reading:{short:4,mid:6,long:4,info:2},listening:{task:6,point:6,summary:3,verbal:4,quick:9}}},
N4:{time:'文字・語彙 25 分；文法・讀解 55 分；聽解 35 分',daily:{vocab:12,grammar:10,reading:6,listening:10},mock:{vocab:{kanji:7,orthography:5,context:8,paraphrase:4,usage:4},grammar:{form:13,composition:4,text:4},reading:{short:3,mid:3,info:2},listening:{task:8,point:7,verbal:5,quick:8}}},
N5:{time:'文字・語彙 20 分；文法・讀解 40 分；聽解 30 分',daily:{vocab:10,grammar:8,reading:5,listening:8},mock:{vocab:{kanji:7,orthography:5,context:6,paraphrase:3},grammar:{form:9,composition:4,text:4},reading:{short:2,mid:2,info:1},listening:{task:7,point:6,verbal:5,quick:6}}}
};
const LABEL={kanji:'漢字讀法',orthography:'表記',wordFormation:'語形成',context:'文脈規定',paraphrase:'言い換え類義',usage:'用法',form:'文の文法1',composition:'文の文法2',text:'文章の文法',short:'內容理解（短篇）',mid:'內容理解（中篇）',long:'內容理解（長篇）',integrated:'綜合理解',thematic:'主張理解（長篇）',info:'信息檢索',task:'課題理解',point:'重點理解',summary:'概要理解',verbal:'發話表現',quick:'即時應答'};
const REASONS=['漢字讀音／表記','語彙','文法','讀解推論','資訊定位','聽解內容','語速／音辨識','粗心','時間不足'];
const TABS=[['vocab','文字・語彙'],['grammar','文法'],['reading','讀解'],['listening','聽解'],['weakness','弱項'],['mock','模擬'],['review','複盤']];
const HIST='jlpt-adaptive-history-v2',LEVELKEY='jlpt-selected-level-v2';
const S={level:localStorage.getItem(LEVELKEY)||'N3',tab:'vocab',answers:{},checked:{},shown:{},reasons:{},sets:{},mockSets:{},notes:''};
const LEX={
N5:[['学校','がっこう','学校で日本語を勉強します。','スクール'],['時間','じかん','時間を確認してください。','とき'],['電車','でんしゃ','電車で会社へ行きます。','列車'],['友達','ともだち','友達と映画を見ました。','友人'],['天気','てんき','今日は天気がいいです。','空模様'],['毎日','まいにち','毎日七時に起きます。','いつも'],['先生','せんせい','先生に質問しました。','教師'],['食事','しょくじ','家族と食事をします。','ごはん'],['病院','びょういん','病院へ行きました。','医院'],['買物','かいもの','駅前で買物をします。','ショッピング'],['休み','やすみ','日曜日は仕事が休みです。','休日'],['電話','でんわ','あとで電話してください。','通話']],
N4:[['準備','じゅんび','旅行の準備を始めました。','用意'],['連絡','れんらく','着いたら家族に連絡します。','知らせること'],['予定','よてい','明日の予定を確認します。','スケジュール'],['間に合う','まにあう','急げば電車に間に合います。','遅れない'],['説明','せつめい','先生が文法を説明しました。','解説'],['経験','けいけん','日本で働いた経験があります。','体験'],['必要','ひつよう','申込には写真が必要です。','要る'],['利用','りよう','この図書館をよく利用します。','使う'],['案内','あんない','駅まで案内してもらいました。','道を教える'],['最近','さいきん','最近、運動を始めました。','このごろ'],['途中','とちゅう','学校へ行く途中で雨が降りました。','道の中ほど'],['変更','へんこう','会議の時間が変更されました。','変えること']],
N3:[['影響','えいきょう','物価の上昇は生活に影響します。','作用'],['確認','かくにん','提出前に内容を確認してください。','確かめる'],['改善','かいぜん','サービスを改善する必要があります。','よくする'],['適切','てきせつ','状況に適切な方法を選びます。','ふさわしい'],['維持','いじ','健康を維持するために運動します。','保つ'],['増加','ぞうか','利用者が去年より増加しました。','増えること'],['減少','げんしょう','交通事故が減少しています。','減ること'],['対象','たいしょう','この調査の対象は大学生です。','当てはまる人'],['目的','もくてき','調査の目的を最初に説明します。','ねらい'],['状況','じょうきょう','現場の状況を詳しく調べました。','様子'],['傾向','けいこう','若者に同じ傾向が見られます。','流れ'],['判断','はんだん','情報を集めてから判断します。','決めること'],['負担','ふたん','費用の負担を減らしたいです。','重荷'],['地域','ちいき','地域の住民と話し合いました。','エリア']],
N2:[['促進','そくしん','交流を促進する制度を作りました。','進める'],['確保','かくほ','安全を確保することが重要です。','守る'],['把握','はあく','利用者の要望を正確に把握します。','理解する'],['配慮','はいりょ','高齢者への配慮が必要です。','気づかい'],['妥当','だとう','その判断が妥当か検討します。','適切'],['慎重','しんちょう','重要な決定は慎重に行います。','注意深い'],['維持','いじ','サービスの質を維持します。','保つ'],['見直す','みなおす','古い制度を見直す必要があります。','再検討する'],['著しい','いちじるしい','人口が著しく増加しました。','非常に大きい'],['円滑','えんかつ','会議を円滑に進める工夫が必要です。','スムーズ'],['削減','さくげん','不要な費用を削減します。','減らす'],['導入','どうにゅう','新しい制度を導入しました。','取り入れる'],['課題','かだい','解決すべき課題が残っています。','問題'],['傾向','けいこう','利用者が増える傾向にあります。','流れ'],['評価','ひょうか','政策の効果を評価します。','価値を判断する']],
N1:[['顕著','けんちょ','地域差が顕著に現れています。','はっきりした'],['踏まえる','ふまえる','調査結果を踏まえて方針を決めます。','考慮する'],['乏しい','とぼしい','その主張は根拠に乏しいです。','不足している'],['阻む','はばむ','複雑な手続きが利用を阻んでいます。','妨げる'],['妥協','だきょう','双方が妥協点を探りました。','譲り合う'],['是正','ぜせい','地域間の格差を是正します。','正す'],['見込む','みこむ','今年は需要の増加を見込んでいます。','予想する'],['覆す','くつがえす','新しい証拠が従来の説を覆しました。','ひっくり返す'],['懸念','けねん','住民から安全性への懸念が示されました。','心配'],['促す','うながす','担当者が早めの申請を促しました。','勧める'],['適宜','てきぎ','状況に応じて適宜対応してください。','必要に応じて'],['一概に','いちがいに','結果だけで一概に判断できません。','一律に'],['趣旨','しゅし','制度の趣旨を理解する必要があります。','目的'],['余儀なく','よぎなく','工事のため計画変更を余儀なくされました。','仕方なく'],['依然','いぜん','問題は依然として残っています。','今もなお']]
};
const GR={
N5:[['雨です（　）、かさを持って行きます。','から',['まで','でも','しか']],['わたしは日本語（　）勉強しています。','を',['が','に','へ']],['駅（　）バスで行きます。','まで',['しか','より','ほど']],['ここで写真を撮って（　）ですか。','もいい',['はいけない','しかない','すぎる']],['昨日、映画を（　）。','見ました',['見ます','見る','見ません']],['朝ご飯を食べ（　）学校へ行きます。','てから',['ながら','ので','なら']],['日本へ（　）ことがあります。','行った',['行く','行って','行き']],['静か（　）部屋が好きです。','な',['に','で','を']]],
N4:[['日本へ来て（　）、すしが好きになりました。','から',['まで','ので','でも']],['雨が降り（　）です。','そう',['よう','らしいに','みたいな']],['早く寝た（　）がいいですよ。','ほう',['だけ','しか','ほど']],['ここでは携帯電話を使っては（　）。','いけません',['ありません','なりませんか','しまいます']],['宿題を忘れ（　）しまいました。','て',['に','が','を']],['時間があれ（　）、一緒に行きませんか。','ば',['ても','ので','のに']],['来週、京都へ行く（　）です。','予定',['経験','必要','途中']],['この本は子ども（　）読めます。','でも',['しか','まで','ほど']],['駅に着い（　）電話してください。','たら',['ながら','ので','まで']]],
N3:[['結果は来週発表される（　）です。','予定',['ところ','わけ','はずがない']],['この薬を飲めば、すぐよくなる（　）。','はずです',['ばかりです','ことです','ようですか']],['忙しい（　）、彼は毎日運動しています。','のに',['ので','ため','なら']],['説明を聞いて（　）、やっと意味が分かりました。','はじめて',['ばかり','ほど','しか']],['この仕事は経験がない人（　）できます。','でも',['しか','こそ','ほど']],['会議は三時から始まること（　）なっています。','に',['を','で','が']],['電車が遅れた（　）、約束に間に合いませんでした。','ため',['ほど','だけ','しか']],['この地域では人口が減り（　）あります。','つつ',['まで','こそ','しか']],['彼の話を聞く（　）、考えが変わりました。','うちに',['わりに','ままに','だけに']],['忘れない（　）メモしておきます。','ように',['ためで','ほどに','しかに']]],
N2:[['この方法は安全性の面（　）問題がある。','で',['を','まで','しか']],['調査結果（　）基づいて計画を見直した。','に',['を','が','へ']],['説明が十分でない（　）、利用者は納得しにくい。','ことには',['わりに','ほどに','だけで']],['彼は忙しい（　）、毎週ボランティアを続けている。','にもかかわらず',['にしたがって','につれて','に対して']],['制度を導入する（　）、十分な準備が必要だ。','にあたって',['にかけて','に沿って','に限って']],['結果がどうであれ、最後までやり（　）。','抜くつもりだ',['かねない','つつある','ざるを得ないか']],['費用だけでなく安全性（　）考慮すべきだ。','も',['しか','こそ','ほど']],['この案は実現できない（　）ではない。','わけ',['もの','こと','ほど']],['担当者は質問に答える（　）、資料も配布した。','とともに',['どころか','にすぎず','に反して']],['人口が増える（　）、交通量も増加した。','につれて',['に先立って','に応じず','に限り']]],
N1:[['十分な検証を行わない（　）、制度を全国に広げるのは危険だ。','ことには',['までもなく','といったら','そばから']],['彼の説明は問題の本質に触れているとは（　）。','言い難い',['言うまでもない','言いかねない','言ってやまない']],['短期的には成功と言える。（　）、長期費用を含めれば結論は異なる。','もっとも',['それゆえ','ひいては','まして']],['制度の趣旨（　）、この運用は適切とは言えない。','に照らして',['に先立って','にかかわらず','に伴って']],['住民の反対を（　）、計画は予定通り進められた。','よそに',['もとに','皮切りに','限りに']],['説明責任を果たさない（　）、信頼回復は難しい。','限り',['だけに','ものの','ところで']],['結果の解釈は条件（　）大きく異なり得る。','いかんで',['を問わず','ならでは','どころか']],['費用削減を重視する（　）、安全性を犠牲にしてはならない。','あまり',['そばから','始末で','なりに']],['政策の効果は数字だけで（　）ものではない。','測れる',['測らざるを得ない','測りかねるべき','測るに足る']],['変更の必要性は認めるが、時期については検討の（　）がある。','余地',['末','極み','きらい']]]
};
const SC={
N5:[['私は','毎朝','七時に','起きます'],['友達と','駅で','十時に','会います'],['昨日','図書館で','本を','読みました']],
N4:[['時間があれば','一緒に','映画を','見ませんか'],['日本へ来てから','毎日','日本語を','勉強しています'],['雨が降りそうなので','傘を','持って','行きます']],
N3:[['この制度について','もっと詳しく','説明して','いただけませんか'],['調査結果を','確認してから','最終案を','決めます'],['住民の意見を','聞くことが','重要だと','思います']],
N2:[['調査結果に','基づいて','計画を','見直しました'],['安全性を','確保するために','手続きを','変更しました'],['利用者の立場を','考慮したうえで','制度を','改善すべきです']],
N1:[['複数の観点を','踏まえたうえで','結論を','導く必要がある'],['短期的な成果だけで','判断することは','必ずしも','妥当ではない'],['制度の趣旨に','照らして考えれば','今回の運用には','疑問が残る']]
};
const READ={
N5:[['山田さんへ。明日のアルバイトは午後三時からです。二時五十分までに店に来てください。',['何時までに店に行きますか。','2時50分',['3時','3時50分','2時30分']],['アルバイトは何時からですか。','3時',['2時50分','4時','2時']]],['図書館は平日9時から20時まで、土曜日は10時から17時までです。日曜日は休みです。',['日曜日に利用できますか。','できません',['できます','午前だけできます','午後だけできます']]]],
N4:[['会議の時間が変わりました。午後2時ではなく午後3時からです。場所は同じ301号室です。',['会議について正しいものはどれですか。','3時から301号室で行う',['2時から301号室で行う','3時から場所も変わる','会議は中止になった']]],['市民プールは平日21時まで、土日は18時までです。毎月第2月曜日は休館です。',['第2月曜日に利用できますか。','利用できません',['18時まで利用できます','21時まで利用できます','午前だけ利用できます']]]],
N3:[['最近、駅前に新しい自転車置き場ができた。以前は放置自転車が多かったが、置き場の利用が広がり、歩道を歩きやすくなった。一方、利用料金が高いという声もある。',['この文章から分かることは何ですか。','歩道は歩きやすくなったが料金への不満もある',['問題は完全に解決した','利用者は減った','置き場は無料だ']],['新しい置き場の効果は何ですか。','放置自転車が減り歩道を使いやすくした',['料金をなくした','駅を移転した','自転車を禁止した']]],['市は来月からごみ収集の曜日を一部変更する。地域によって新しい曜日が異なるため、市のウェブサイトか配布された表で確認する必要がある。',['住民は何をする必要がありますか。','自分の地域の新しい収集曜日を確認する',['毎日ごみを出す','市役所へ行く','収集をやめる']]]],
N2:[['在宅勤務は通勤時間を減らす一方、仕事と私生活の境界を曖昧にすることがある。重要なのは、どちらが優れていると単純に決めることではなく、仕事内容や家庭環境に応じて働き方を設計することだ。',['筆者の主張は何ですか。','状況に応じて働き方を設計すべきだ',['在宅勤務は常に優れている','出勤だけが望ましい','家庭環境は関係ない']]],['公共施設を増やすだけでは利用は広がらない。利用時間、料金、交通手段など、実際に使う人の条件を同時に考える必要がある。',['筆者が重要だと考えていることは何ですか。','利用者の条件も含めて考えること',['施設数だけを増やすこと','料金を必ず無料にすること','交通を無視すること']]]],
N1:[['制度設計では、選択肢を増やすことが常に自由の拡大につながるとは限らない。選択肢が多すぎれば比較に必要な情報や時間も増える。重要なのは数ではなく、利用者が違いを理解し、自分の目的に合った選択をできるよう情報を整理することだ。',['筆者が最も重視していることは何か。','選択肢の違いを理解できるよう情報を整理すること',['選択肢をできるだけ多くすること','利用者に比較させないこと','制度を一つに統一すること']]],['データに基づく政策判断は重要だが、何をデータとして採用するかという段階ですでに価値判断が入り込む。したがって「数字に基づくから中立」と考えるのではなく、指標の選び方そのものを検討対象にすべきである。',['筆者の主張は何か。','指標の選択自体にも価値判断があることを意識すべきだ',['数字を使う判断はすべて誤りだ','測定しにくいものは除外すべきだ','データがあれば完全に中立だ']]]]
};
const LISTEN={
N5:[['すみません、今、何時ですか。','最も自然な答えはどれですか。','三時です。',['学生です。','駅です。','毎日です。']],['女の人：あした、駅で十時に会いましょう。男の人：十時ですね。わかりました。','二人は何時に会いますか。','10時',['9時','11時','12時']]],
N4:[['店員：いらっしゃいませ。何をお探しですか。','客として最も自然な返事はどれですか。','白いシャツを探しています。',['毎日働いています。','駅へ行きました。','三人います。']],['男の人：土曜日は雨らしいですよ。女の人：じゃあ、山へ行くのは日曜日にしましょう。','二人はいつ山へ行きますか。','日曜日',['土曜日','金曜日','月曜日']]],
N3:[['女の人：資料は今日中にメールで送ってください。男の人：わかりました。帰ったらすぐ送ります。','男の人はこのあと何をしますか。','資料をメールで送る',['資料を印刷する','会議を中止する','電話を待つ']],['男の人：駅前の店は混んでいるから、少し離れた店にしませんか。女の人：そうしましょう。','二人はどこへ行きますか。','駅から少し離れた店',['駅前の店','駅の中','家']]],
N2:[['女の人：会議資料は完成しましたが、数字の部分をもう一度確認してから配布してください。男の人：はい、確認後に配ります。','男の人が最初にすることは何ですか。','数字を確認する',['資料を配布する','会議を中止する','資料を捨てる']],['男の人：利用者は増えていますが、満足度は下がっています。数だけでは成功とは言えませんね。','男の人が言いたいことは何ですか。','利用者数だけで評価すべきではない',['利用者は減っている','満足度だけを見ればよい','調査は不要だ']]],
N1:[['女の人：最終案は今日中にまとめます。あなたは関係部署に、明日の会議までに意見を送ってほしいと連絡してもらえますか。男の人：承知しました。','男の人は何をしますか。','関係部署に意見提出を依頼する',['最終案をまとめる','会議を延期する','意見を削除する']],['男の人：調査対象を広げればデータは増えますが、比較条件がそろわなくなる恐れがあります。今回は範囲を限定し、同じ基準で詳しく見るほうがいいでしょう。','男の人はどの方法を勧めていますか。','対象を限定して同じ基準で詳しく調べる',['対象をできるだけ増やす','比較をやめる','基準を毎回変える']]]
};
const WF=[['計画を（　）検討する。','再',['未','非','無']],['内容を（　）確認してください。','再',['不','非','最']],['この商品は（　）使用できます。','再',['無','否','逆']],['（　）公開の資料です。','未',['再','過','全']],['事故を（　）防止する。','再',['半','外','先']]];
function dkey(){const d=new Date(),p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m))}
function hist(){try{return JSON.parse(localStorage.getItem(HIST)||'{}')||{}}catch(e){return{}}}
function prior(skill){const a=hist()?.[S.level]?.[skill]||[];return a.filter(x=>x.date<dkey()).sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function tier(skill){const p=prior(skill);if(!p)return 0;return p.acc<.6?0:p.acc<.8?1:p.acc<.9?2:3}
const TL=['基礎','標準','進階','挑戰'];
function record(skill,qs){const done=qs.filter(q=>S.answers[q.id]);if(!done.length){alert('請先作答至少一題。');return}const ok=done.filter(q=>S.answers[q.id]===q.a).length,acc=ok/done.length;const wrong={};done.filter(q=>S.answers[q.id]!==q.a).forEach(q=>wrong[q.type]=(wrong[q.type]||0)+1);const rc={};done.forEach(q=>{const r=S.reasons[q.id];if(r)rc[r]=(rc[r]||0)+1});const h=hist();h[S.level]??={};h[S.level][skill]??=[];const arr=h[S.level][skill],it={date:dkey(),acc,wrong,reason:rc,ts:Date.now()},i=arr.findIndex(x=>x.date===it.date);if(i>=0)arr[i]=it;else arr.push(it);h[S.level][skill]=arr.slice(-30);localStorage.setItem(HIST,JSON.stringify(h));alert('本區 '+ok+'/'+done.length+'，正確率 '+Math.round(acc*100)+'%。已記錄，下一個練習日會自動調整。')}
function typePlan(skill,count){const bp=OFFICIAL[S.level].mock[skill],arr=[];Object.entries(bp).forEach(([t,n])=>{for(let i=0;i<n;i++)arr.push(t)});const p=prior(skill),weak=p?Object.entries(p.wrong||{}).sort((a,b)=>b[1]-a[1]).map(x=>x[0]).slice(0,2):[];const out=[];for(let i=0;i<count;i++){if(weak.length&&i<Math.min(4,count))out.push(weak[i%weak.length]);else out.push(arr[i%arr.length])}return out}
function distract(list,correct,n=3){return list.filter(x=>x!==correct).slice(0,n)}
function qid(skill,type,i,mode){return [mode,S.level,skill,type,dkey(),i].join('|')}
function vocabQ(type,i,seed,mode){const r=rng(seed+i*97),bank=LEX[S.level],x=bank[Math.floor(r()*bank.length)],others=shuffle(bank.filter(y=>y!==x),r);let p='',a='',o=[];if(type==='kanji'){p='「'+x[0]+'」の読み方として最も適切なものを選んでください。';a=x[1];o=[a,...others.slice(0,3).map(y=>y[1])]}else if(type==='orthography'){p='「'+x[1]+'」の表記として最も適切なものを選んでください。';a=x[0];o=[a,...others.slice(0,3).map(y=>y[0])]}else if(type==='wordFormation'){const z=WF[i%WF.length];p=z[0];a=z[1];o=[a,...z[2]]}else if(type==='context'){p=x[2].replace(x[0],'（　）');a=x[0];o=[a,...others.slice(0,3).map(y=>y[0])]}else if(type==='paraphrase'){p='「'+x[0]+'」に最も近い意味を選んでください。';a=x[3];o=[a,...others.slice(0,3).map(y=>y[3])]}else{p='「'+x[0]+'」の使い方として最も適切なものを選んでください。';a=x[2];o=[a,'昨日、'+x[0]+'を食べました。',x[0]+'が駅へ歩きました。','私は'+x[0]+'を三時です。']}return{id:qid('vocab',type,i,mode),skill:'vocab',type,p,a,o:shuffle(o,r),e:'正解：'+a}}
function grammarQ(type,i,seed,mode){const r=rng(seed+i*131),bank=GR[S.level],x=bank[Math.floor(r()*bank.length)];if(type==='composition'){const c=SC[S.level][i%SC[S.level].length],star=2,opts=shuffle(c,r);return{id:qid('grammar',type,i,mode),skill:'grammar',type,p:'次の語句を正しい順序に並べたとき、★に入るものを選んでください。\n'+c[0]+'　＿＿　＿＿　★　＿＿',a:c[star],o:opts,e:'正しい語順：'+c.join(' ')}}const p=type==='text'?'文脈に最も自然につながるものを選んでください。\n'+x[0]:x[0];return{id:qid('grammar',type,i,mode),skill:'grammar',type,p,a:x[1],o:shuffle([x[1],...x[2]],r),e:'この文脈では「'+x[1]+'」が最も自然です。'}}
function readingQ(type,i,seed,mode){const r=rng(seed+i*173),bank=READ[S.level],z=bank[Math.floor(r()*bank.length)],q=z[1+((i+Math.floor(r()*7))%(z.length-1))];return{id:qid('reading',type,i,mode),skill:'reading',type,pass:z[0],p:q[0],a:q[1],o:shuffle([q[1],...q[2]],r),e:'本文の内容に最も合うのは「'+q[1]+'」です。'}}
function listenQ(type,i,seed,mode){const r=rng(seed+i*199),bank=LISTEN[S.level],z=bank[Math.floor(r()*bank.length)];return{id:qid('listening',type,i,mode),skill:'listening',type,audio:z[0],p:z[1],a:z[2],o:shuffle([z[2],...z[3]],r),e:'音声内容から「'+z[2]+'」が正解です。'}}
function make(skill,type,i,seed,mode){return skill==='vocab'?vocabQ(type,i,seed,mode):skill==='grammar'?grammarQ(type,i,seed,mode):skill==='reading'?readingQ(type,i,seed,mode):listenQ(type,i,seed,mode)}
function dailySet(skill){const key=[S.level,skill,dkey()].join('|');if(S.sets[key])return S.sets[key];const count=OFFICIAL[S.level].daily[skill],types=typePlan(skill,count),seed=hash('daily|'+key);return S.sets[key]=types.map((t,i)=>make(skill,t,i,seed,'daily'))}
function mockSet(skill){const key=[S.level,skill,dkey()].join('|');if(S.mockSets[key])return S.mockSets[key];const bp=OFFICIAL[S.level].mock[skill],seed=hash('mock|'+key),arr=[];let i=0;Object.entries(bp).forEach(([t,n])=>{for(let k=0;k<n;k++)arr.push(make(skill,t,i++,seed,'mock'))});return S.mockSets[key]=arr}
function reason(q){const cur=S.reasons[q.id]||'';return '<div class="reason"><b>錯題原因</b><select data-reason="'+esc(q.id)+'"><option value="">未選擇錯題原因</option>'+REASONS.map(x=>'<option '+(cur===x?'selected':'')+'>'+esc(x)+'</option>').join('')+'</select></div>'}
function card(q){const sel=S.answers[q.id]||'',show=S.shown[q.id],chk=S.checked[q.id];const opts=q.o.map((o,i)=>{let c='opt';if(show&&o===q.a)c+=' good';if(show&&sel===o&&o!==q.a)c+=' bad';return '<label class="'+c+'"><input type="radio" name="'+esc(q.id)+'" value="'+esc(o)+'" '+(sel===o?'checked':'')+'> <span>'+String.fromCharCode(65+i)+'. '+esc(o)+'</span></label>'}).join('');const audio=q.audio?'<div class="audio"><button type="button" data-speak="'+esc(q.audio)+'">▶ 播放音檔</button><span class="small">可重複播放</span></div>':'';const pass=q.pass?'<div class="passage jp">'+esc(q.pass)+'</div>':'';const fb=chk?'<div class="feedback '+(sel===q.a?'good':'bad')+'">'+(sel===q.a?'✓ 正確':'✗ 再檢查一次')+'</div>':'';const ans=show?'<div class="accent"><b>正確答案：</b><span class="jp">'+esc(q.a)+'</span><br><span class="small">'+esc(q.e)+'</span></div>':'';return '<article class="q"><h3>'+esc(LABEL[q.type]||q.type)+'</h3>'+pass+audio+'<div class="prompt jp">'+esc(q.p).replace(/\n/g,'<br>')+'</div><div class="opts">'+opts+'</div><div class="actions"><button class="btn" data-check="'+esc(q.id)+'">檢查答案</button><button class="btn" data-show="'+esc(q.id)+'">顯示答案</button></div>'+fb+ans+reason(q)+'</article>'}
function weakText(skill){const p=prior(skill);if(!p)return'無前次紀錄';const w=Object.entries(p.wrong||{}).sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>LABEL[x[0]]||x[0]);return w.length?'前次弱項：'+w.join('、'):'前次沒有明顯集中弱項'}
function skillView(skill,title){const qs=dailySet(skill),p=prior(skill);return '<div class="section-title">'+title+'｜今日 '+qs.length+' 題</div><div class="accent"><b>今日難度：'+TL[tier(skill)]+'</b><br><span class="small">'+(p?'上次正確率 '+Math.round(p.acc*100)+'%；'+weakText(skill)+'。本日題型比例已自動調整。':'無前次紀錄，使用簡單基準。')+' 今日題組由日期＋級數固定產生，明天會換一批。</span></div>'+qs.map(card).join('')+'<button class="btn primary" data-finish="'+skill+'">完成本區並記錄</button>'}
function mockGroups(){if(['N1','N2'].includes(S.level))return[['lang','言語知識・讀解',['vocab','grammar','reading']],['listening','聽解',['listening']]];return[['vocab','文字・語彙',['vocab']],['gr','文法・讀解',['grammar','reading']],['listening','聽解',['listening']]]}
function totalFor(skills){return skills.reduce((s,k)=>s+Object.values(OFFICIAL[S.level].mock[k]).reduce((a,b)=>a+b,0),0)}
function mockHome(){return '<div class="section-title">'+S.level+' 官方題數基準 Full Mock</div><div class="accent"><b>官方基準時間：</b>'+esc(OFFICIAL[S.level].time)+'<br><span class="small">題數依官方公布的「問題數目安／基準」配置；實際正式考試題數可能略有差異。本站題目均為原創練習題。</span></div><div class="mockgrid">'+mockGroups().map(g=>'<div class="mockcard"><b>'+g[1]+'</b><div class="small">'+totalFor(g[2])+' 題</div><button class="btn primary" data-mockgroup="'+g[0]+'">開始此測驗區段</button></div>').join('')+'</div><div id="mockArea"></div>'}
function renderMockGroup(code){const g=mockGroups().find(x=>x[0]===code);if(!g)return;const qs=g[2].flatMap(mockSet);document.getElementById('mockArea').innerHTML='<div class="section-title mock-title">'+g[1]+'｜'+qs.length+' 題</div><div class="accent small">此區依官方題數基準完整產生。完成後顯示 raw accuracy；JLPT 正式成績採尺度分數，本站不把 raw accuracy 假裝成官方分數。</div>'+qs.map(card).join('')+'<button class="btn primary" data-finishmock="'+g[0]+'">完成此 Mock 區段</button>';document.getElementById('mockArea').scrollIntoView({behavior:'smooth',block:'start'})}
function weakView(){const rows=['vocab','grammar','reading','listening'].map(s=>{const p=prior(s);return '<div class="stat"><span>'+({vocab:'文字・語彙',grammar:'文法',reading:'讀解',listening:'聽解'}[s])+'</span><b>'+(p?Math.round(p.acc*100)+'%':'—')+'</b></div>'}).join('');return '<div class="section-title">錯題自適應</div><div class="accent"><b>前次各科表現</b><div class="stats">'+rows+'</div></div><p class="small">下一個練習日會自動把更多題目分配給前次錯誤較集中的題型，並依正確率調整難度。</p>'}
function reviewView(){return '<div class="section-title">複盤</div><div class="accent"><b>本輪狀態</b><div class="small">已作答 '+Object.keys(S.answers).length+' 題；已標記錯題原因 '+Object.values(S.reasons).filter(Boolean).length+' 題。</div></div><textarea id="innerNotes" placeholder="寫下今天最重要的 2 個弱項與下一次改善動作。">'+esc(S.notes)+'</textarea>'}
function reasonStats(){const c=Object.fromEntries(REASONS.map(x=>[x,0]));Object.values(S.reasons).forEach(x=>{if(x)c[x]++});document.getElementById('stats').innerHTML=REASONS.map(x=>'<div class="stat"><span>'+x+'</span><b>'+c[x]+'</b></div>').join('');document.getElementById('marked').textContent='本輪已標記 '+Object.values(S.reasons).filter(Boolean).length+' 題'}
function render(){document.querySelectorAll('.level').forEach(b=>b.classList.toggle('on',b.dataset.level===S.level));document.getElementById('summary').textContent=S.level+'｜'+OFFICIAL[S.level].time;document.getElementById('difficulty').innerHTML='<b>每日自動新題＋錯題自適應</b><br><span class="small">今日題組日期：'+dkey()+'。重新載入會清空本輪作答，但保留歷史正確率／弱項摘要供下一個練習日調整。</span>';document.getElementById('tabs').innerHTML=TABS.map(x=>'<button class="tab '+(S.tab===x[0]?'on':'')+'" data-tab="'+x[0]+'">'+x[1]+'</button>').join('');let h='';if(S.tab==='vocab')h=skillView('vocab','文字・語彙');else if(S.tab==='grammar')h=skillView('grammar','文法');else if(S.tab==='reading')h=skillView('reading','讀解');else if(S.tab==='listening')h=skillView('listening','聽解');else if(S.tab==='weakness')h=weakView();else if(S.tab==='mock')h=mockHome();else h=reviewView();document.getElementById('content').innerHTML=h;reasonStats()}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ja-JP';u.rate=.9;const v=speechSynthesis.getVoices().find(x=>/^ja/i.test(x.lang));if(v)u.voice=v;speechSynthesis.speak(u)}catch(e){alert('目前瀏覽器無法播放日語語音。')}}
document.addEventListener('change',e=>{if(e.target.matches('input[type=radio]'))S.answers[e.target.name]=e.target.value;if(e.target.matches('[data-reason]')){S.reasons[e.target.dataset.reason]=e.target.value;reasonStats()}});
document.addEventListener('input',e=>{if(e.target.id==='innerNotes'||e.target.id==='notes'){S.notes=e.target.value}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.level){S.level=b.dataset.level;localStorage.setItem(LEVELKEY,S.level);S.tab='vocab';S.answers={};S.checked={};S.shown={};S.reasons={};S.sets={};S.mockSets={};render();return}if(b.dataset.tab){S.tab=b.dataset.tab;render();return}if(b.dataset.check){if(!S.answers[b.dataset.check]){alert('請先選擇答案。');return}S.checked[b.dataset.check]=true;render();return}if(b.dataset.show){S.shown[b.dataset.show]=true;render();return}if(b.dataset.speak){speak(b.dataset.speak);return}if(b.dataset.finish){record(b.dataset.finish,dailySet(b.dataset.finish));render();return}if(b.dataset.mockgroup){renderMockGroup(b.dataset.mockgroup);return}if(b.dataset.finishmock){const g=mockGroups().find(x=>x[0]===b.dataset.finishmock);const qs=g[2].flatMap(mockSet),done=qs.filter(q=>S.answers[q.id]);if(!done.length){alert('請先作答。');return}const ok=done.filter(q=>S.answers[q.id]===q.a).length;alert('Mock raw：'+ok+'/'+done.length+'（'+Math.round(ok/done.length*100)+'%）。正式 JLPT 為尺度分數，本站 raw accuracy 不等同正式分數。');return}});
render();
})();