name: TOEFLStudyLab
options:
  bundleIdPrefix: tw.leon
  deploymentTarget:
    iOS: '15.0'
settings:
  base:
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0.57
    CURRENT_PROJECT_VERSION: 57
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 13.7.0
  UserMessagingPlatform:
    url: https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git
    from: 3.1.0
targets:
  TOEFLStudyLab:
    type: application
    platform: iOS
    sources:
      - TOEFLStudyLab
    dependencies:
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: UserMessagingPlatform
        product: GoogleUserMessagingPlatform
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tw.leon.toeflstudy
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: TOEFLStudyLab/Info.plist
        TARGETED_DEVICE_FAMILY: '1,2'
        CODE_SIGN_STYLE: Automatic
        OTHER_LDFLAGS: '$(inherited) -ObjC'
