plugins {
    id 'com.android.application'
}

android {
    namespace 'tw.leon.toeflstudy'
    compileSdk 35

    defaultConfig {
        applicationId 'tw.leon.toeflstudy'
        minSdk 26
        targetSdk 35
        versionCode 57
        versionName '1.0.57'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
    implementation 'com.google.android.ump:user-messaging-platform:4.0.0'
}
