name: JLPTStudyLab
options:
  bundleIdPrefix: tw.ozisun
  deploymentTarget:
    iOS: "15.0"

targets:
  JLPTStudyLab:
    type: application
    platform: iOS
    sources:
      - JLPTStudyLab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tw.ozisun.jlptstudylab
        PRODUCT_NAME: JLPTStudyLab
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: JLPTStudyLab/Info.plist
