name: JLPTStudyLab
options:
  bundleIdPrefix: tw.ozisun
  deploymentTarget:
    iOS: "15.0"

packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 12.0.0
  GoogleUserMessagingPlatform:
    url: https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git
    from: 3.0.0

targets:
  JLPTStudyLab:
    type: application
    platform: iOS
    sources:
      - JLPTStudyLab
    dependencies:
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: GoogleUserMessagingPlatform
        product: GoogleUserMessagingPlatform
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tw.ozisun.jlptstudylab
        PRODUCT_NAME: JLPTStudyLab
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: JLPTStudyLab/Info.plist
